
title: mathematician
url: 'littleome.ga'
baseurl: '' #change it according to your repository name



# Profile information
yourname: Almog A. Dubin  ## put your name
title: 'mathematician &amp; data scientist '  ## your title
location: Yavne , IL


## Social Profiles
facebook: https://www.facebook.com/almog.dubin  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://il.linkedin.com/in/almog-dubin-281a046b  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
